# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.9

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
#variables:
#  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - .cache/apt
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - export PIP_CACHE_DIR=`pwd`/.cache/pip
  - export APT_CACHE_DIR=`pwd`/.cache/apt
  - pip install --cache-dir "$PIP_CACHE_DIR" --upgrade pip
  - pip install --cache-dir "$PIP_CACHE_DIR" virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install --cache-dir "$PIP_CACHE_DIR" tensorflow==2.6
  - pip install --cache-dir "$PIP_CACHE_DIR" keras
  - pip install --cache-dir "$PIP_CACHE_DIR" scikit-learn
  - pip install --cache-dir "$PIP_CACHE_DIR" scipy
  - pip install --cache-dir "$PIP_CACHE_DIR" matplotlib
  - pip install --cache-dir "$PIP_CACHE_DIR" pandas
  - pip install --cache-dir "$PIP_CACHE_DIR" pyyaml
  - apt-get update
  - apt-get -o Dir::Cache::Archives="$APT_CACHE_DIR" install -yqq gfortran
  - apt-get -o Dir::Cache::Archives="$APT_CACHE_DIR" install -yqq latexmk
  - apt-get -o Dir::Cache::Archives="$APT_CACHE_DIR" install -yqq xzdec
  - apt-get -o Dir::Cache::Archives="$APT_CACHE_DIR" install -yqq texlive-fonts-recommended
  - apt-get -o Dir::Cache::Archives="$APT_CACHE_DIR" install -yqq texlive-latex-recommended
  - apt-get -o Dir::Cache::Archives="$APT_CACHE_DIR" install -yqq texlive-latex-extra
    #- apt-get -o Dir::Cache::Archives="$APT_CACHE_DIR" install -yqq libnvinfer-plugin6=6.0.1-1+cuda10.1

test:
  stage: test
  script:
    - export PYTHONPATH="/builds/NRAP-IAM/UQ_example_setup/:$PYTHONPATH"
    - echo $PYTHONPATH
    - cd setup
    - python openiam_setup_tests.py

      #run:
      #  script:
      #    - python setup.py bdist_wheel
      #    # an alternative approach is to install and run:
      #    - pip install dist/*
      #    # run the command here
      #  artifacts:
      #    paths:
      #      - dist/*.whl

pages:
  stage: deploy
  script:
    - pip install sphinx sphinx-rtd-theme sphinxcontrib-bibtex==1.0 sphinx_numfig
    - cd documentation/website ; make html
    - mv build/html/ ../../public/
  artifacts:
    paths:
      - public
        #only:
        #- master

stages:
  - test
  - deploy
