# -*- coding: utf-8 -*-
"""
This module contains description of control file and GUI setup examples,
filenames, and main features (for control file interface examples) illustrated
in them.
"""
GUI_EXAMPLES = [
    '01_Forward_AR_CW.OpenIAM',
    '02_LHS_AR_MSW.OpenIAM',
    '03_LHS_LUT_MSW.OpenIAM',
    '04_LHS_DP_MSW.OpenIAM',
    '05_LHS_AR_OW_CA.OpenIAM',
    '06_LHS_AR_OW_ATM.OpenIAM',
    '07_LHS_LUT_MSW_FG2AZ.OpenIAM',
    '08_PARSTUDY_PSA.OpenIAM',
    '09_Forward_LUT_SH.OpenIAM',
    '10_LHS_MSW_GENAQ.OpenIAM',
    '11_LHS_AR_CWWR.OpenIAM',
    '12_LHS_FL.OpenIAM',
    '13_Forward_TR.OpenIAM',
    '14_Forward_HCL.OpenIAM',
    ]

CFI_EXAMPLES = {
    '1a': 'Analytical reservoir, Cemented wellbore, forward',
    '1b': 'Analytical reservoir, Cemented wellbore, forward, plots: line setup options',
    '2': 'Analytical reservoir, Multisegmented wellbore, LHS',
    '3': 'Analytical reservoir, Multisegmented wellbore, Carbonate aquifer, LHS',
    '4a': 'Analytical reservoir, Open wellbore, Carbonate aquifer, LHS',
    '4b': 'Analytical reservoir, Open wellbore (multiple locations), critical pressure, forward',
    '5': 'Analytical reservoir, Cemented wellbore, parstudy',
    '6': 'LUT reservoir, Multisegmented wellbore, LHS',
    '7a': 'Multisegmented wellbore, LHS, dyn_pars: arrays',
    '7b': 'Multisegmented wellbore, LHS, dyn_pars: filenames',
    '8a': 'Analytical reservoir, Multisegmented wellbore, LHS, sensitivity analysis plot options',
    '8b': 'Analytical reservoir, Multisegmented wellbore, LHS, sensitivity analysis plot options',
    '8c': 'Analytical reservoir, Open wellbore, FutureGen2 aquifer, LHS, sensitivity analysis plot options',
    '9a': 'Analytical reservoir, Open wellbore, Atmospheric ROM, LHS, atm plume plot',
    '9b': 'Analytical reservoir, Open wellbore, Atmospheric ROM, forward, atm plume plot',
    '9c': 'LUT reservoir, Open wellbore, Atmospheric ROM, LHS, atm plume plot',
    '10': 'LUT reservoir, Cemented wellbore, Deep alluvium aquifer, LHS',
    '11': ''.join(['Analytical reservoir, Multisegmented wellbore ',
                   '(multiple locations), Carbonate aquifer, forward']),
    '12': 'Generalized flow rate, forward',
    '13': 'Generalized flow rate (multiple locations), Carbonate aquifer, forward',
    '14': 'LUT reservoir, Multisegmented wellbore (multiple locations), FutureGen2 aquifer, LHS',
    '15': 'LUT reservoir, Multisegmented wellbore (multiple locations), FutureGen2 AZMI, LHS',
    '16': 'Plume stability analysis, parstudy',
    '17': 'Fault flow, forward, dyn_pars: arrays',
    '18': 'LUT reservoir, fault flow, GriddedMetric plot, LHS',
    '19': 'LUT reservoir, seal horizon, GriddedMetric plot, LHS',
    '20': 'Analytical reservoir, LHS',
    '21': 'Multisegmented wellbore, Deep alluvium aquifer (ML), dyn_pars: filenames, forward',
    '22': 'Chemical well sealing, forward',
    '23': 'LUT reservoir, Seal Horizon, GriddedMetric plot, forward',
    '24': 'LUT reservoir, Multisegmented wellbore, Generic Aquifer, forward',
    '25': 'Multisegmented wellbore, Generic Aquifer, LHS, dyn_pars: arrays',
    '26': ''.join(['LUT reservoir, Multisegmented wellbore (multiple locations), ',
                   'FutureGen2 aquifer, 3d interpolation, forward']),
    '27': 'LUT reservoir, Multisegmented wellbore, Temperature metric, forward',
    '28': 'LUT reservoir, Multisegmented wellbore, additional metric, forward',
    '29': ''.join(['LUT reservoir, Multisegmented wellbore (multiple locations), ',
                   'random locations domain, 3d interpolation, forward']),
    '30': ''.join(['LUT reservoir, Multisegmented wellbore, multiple locations, ',
                   'setup options for locations, plot figsize, forward']),
    '31a': 'Analytical reservoir, Open wellbore, FutureGen2 aquifer, AoR setup, forward',
    '31b': 'Analytical reservoir, Open wellbore, Generic aquifer, AoR setup, forward',
    '31c': 'Analytical reservoir, Open wellbore, FutureGen2 aquifer, AoR setup, LHS',
    '31d': 'Analytical reservoir, Open wellbore, FutureGen2 aquifer, AoR setup, TimeList option, LHS',
    '31e': 'Analytical reservoir, Cemented wellbore, FutureGen2 aquifer, AoR setup, forward',
    '31f': 'Analytical reservoir, Multisegmented wellbore, FutureGen2 aquifer, AoR setup, forward',
    '32a': ''.join(['LUT reservoir, Open wellbore, FutureGen2 aquifer, ',
                    'AoR setup, 3d interpolation, forward']),
    '32b': ''.join(['LUT reservoir, Open wellbore, FutureGen2 aquifer, ',
                    'AoR setup, lookup table stratigraphy, stratigraphy plot, ',
                    'well locations from file, forward']),
    '32c': ''.join(['LUT reservoir, Open wellbore, FutureGen2 aquifer, ',
                    'AoR setup, TimeList option, lookup table stratigraphy, ',
                    'stratigraphy plot, well locations from file, forward']),
    '33a': ''.join(['Analytical reservoir, Open wellbore, ',
                   'spatially variable stratigraphy (strike and dip), ',
                   'stratigraphy plot, stratigraphic column plot, forward']),
    '33b': ''.join(['Analytical reservoir, Open wellbore, ',
                   'spatially variable stratigraphy (strike and dip), ',
                   'stratigraphy plot, stratigraphic column plot (advanced ',
                   'options), forward']),
    '34': ''.join(['Analytical reservoir, Open wellbore, Generic aquifer, ',
                   'spatially variable stratigraphy (strike, dip, and ',
                   'reference point, string definition of parameters ',
                   'dependent on stratigraphy, ',
                   'stratigraphy plot, forward']),
    '35': ''.join(['Analytical reservoir, Open wellbore, ',
                   'spatially variable stratigraphy (strike, dip, and ',
                   'reference point, string definition of parameters ',
                   'dependent on stratigraphy, well locations defined by grid, ',
                   'stratigraphy plot/tiff format, forward']),
    '36': ''.join(['Analytical reservoir, Open wellbore, Generic aquifer, ',
                   'string definition of parameters dependent on stratigraphy, ',
                   'well locations defined by grid, ',
                   'stratigraphy plot, forward']),
    '37': ''.join(['LUT reservoir, Multisegmented wellbore, ',
                   'multiple plots, including stratigraphy plot, in ',
                   'tiff format, forward']),
    '38': ''.join(['Simple reservoir, Open wellbore, ',
                   'lookup table stratigraphy, string definition ',
                   'of parameters dependent on stratigraphy, ',
                   'well locations from file, stratigraphy plot, forward']),
    '39a': ''.join(['Analytical reservoir, Multisegmented wellbore, ',
                    'FutureGen2 AZMI, LHS, TTFD plot for TDS']),
    '39b': ''.join(['Analytical reservoir, Multisegmented wellbore, ',
                    'FutureGen2 AZMI, spatially varying stratigraphy, ',
                    'stratigraphy plot, forward, TTFD plot for pH']),
    '40': ''.join(['LUT reservoir, Multisegmented wellbore, ',
                   'FutureGen2 AZMI for 2 aquifers, LHS, TTFD plot for ',
                   'Dissolved CO2']),
    '41': ''.join(['Analytical reservoir, Open wellbore (multiple locations), ',
                   'Generic Aquifer, forward, TTFD plot for Dissolved Salt']),
    '42': ''.join(['Analytical reservoir, Multisegmented wellbore (multiple locations), ',
                   'Carbonate Aquifer, LHS, TTFD plot']),
    '43': ''.join(['Analytical reservoir, Multisegmented wellbore (multiple locations), ',
                   'Deep Alluvium Aquifer, LHS, TTFD plot for TDS']),
    '44a': ''.join(['Theis Reservoir, forward, based on script iam_sys_theis.py, ',
                    'injRates and injTimes provided as lists, ',
                    'single injection well']),
    '44b': ''.join(['Theis Reservoir, LHS, based on script iam_sys_theis.py, ',
                    'injRates and injTimes provided as lists, ',
                    'single injection well']),
    '45a': ''.join(['Theis Reservoir, forward, based on script iam_sys_theis_benchmark2.py, ',
                    'injRates and injTimes provided as lists, ',
                    'single injection well']),
    '45b': ''.join(['Theis Reservoir, forward, based on script iam_sys_theis_benchmark2.py, ',
                    'injRates and injTimes provided through separate input files, ',
                    'single injection well']),
    '45c': ''.join(['Theis Reservoir, forward, based on script iam_sys_theis_benchmark2.py, ',
                    'injRates and injTimes provided through separate input files, ',
                    'single injection well']),
    '45d': ''.join(['Theis Reservoir, forward, based on script iam_sys_theis_benchmark2.py, ',
                    'injRates and injTimes provided through a single input file, ',
                    'single injection well']),
    '46a': ''.join(['Theis Reservoir, forward, based on script iam_sys_theis_4inj.py, ',
                    'injRates and injTimes provided as lists, ',
                    'multiple injection wells']),
    '46b': ''.join(['Theis Reservoir, forward, based on script iam_sys_theis_4inj.py, ',
                    'injRates and injTimes provided through separate input files, ',
                    'multiple injection wells']),
    '47': ''.join(['Generic Reservoir, forward, multiple locations']),
    '48': 'Fault flow, forward, time points from input file, dyn_pars: arrays',
    '49': 'Fault flow, forward, time points from input file, dyn_pars: arrays',
    '50': 'Analytical reservoir, fault flow, LHS',
    '51a': ''.join(['Analytical reservoir, cemented wellbore (wr) (multiple locations), ',
                    'random locations domain, forward']),
    '51b': ''.join(['Analytical reservoir, cemented wellbore (wr) (multiple locations), ',
                    'random locations domain, LHS']),
    '51c': ''.join(['Analytical reservoir, cemented wellbore (wr) (multiple locations), ',
                    'random locations domain, forward']),
    '52a': 'Hydrocarbon leakage, forward',
    '52b': 'Hydrocarbon leakage, LHS',
    '53a': 'Fault leakage, forward',
    '53b': 'Fault leakage, LHS',
    '54a': ''.join(['Analytical reservoir, Open wellbore, Generic aquifer, ',
                    'GriddedRadialMetric plot, forward']),
    '54b': ''.join(['Analytical reservoir, Open wellbore, Generic aquifer, ',
                    'GriddedRadialMetric plot (default settings), forward']),
    '54c': ''.join(['LUT reservoir, Multisegmented wellbore, Generic aquifer, ',
                    'GriddedRadialMetric plot, forward']),
    '54d': ''.join(['Analytical reservoir, Open wellbore, Generic aquifer, ',
                    'GriddedRadialMetric plot, LHS']),
    '55a': 'LUT reservoir, Open wellbore, FutureGen2 aquifer, Workflow: AoR, forward',
    '55b': ''.join(['LUT reservoir, Open wellbore, FutureGen2 aquifer, ',
                    'Workflow: AoR, spatially variable stratigraphy, forward']),
    '55c': ''.join(['LUT reservoir, Open wellbore, Generic aquifer, ',
                    'Workflow: AoR, default settings, forward']),
    '55d': ''.join(['LUT reservoir, Open wellbore, FutureGen2 aquifer, ',
                    'Workflow: AoR, spatially variable stratigraphy, time list option']),
    '56a': ''.join(['Analytical reservoir, Open wellbore, Generic aquifer, ',
                    'Workflow: AoR, simple settings, forward']),
    '56b': ''.join(['Analytical reservoir, Open wellbore, FutureGen2 aquifer, ',
                    'Workflow: AoR, AoR plots, forward']),
    '56c': ''.join(['Analytical reservoir, Open wellbore, FutureGen2 aquifer, ',
                    'Workflow: AoR, forward']),
    '56d': ''.join(['Analytical reservoir, Open wellbore, FutureGen2 aquifer, ',
                    'Workflow: AoR, LHS']),
    '56e': ''.join(['Analytical reservoir, Multisegmented wellbore, FutureGen2 aquifer, ',
                    'Workflow: AoR, forward']),
    '56f': ''.join(['Analytical reservoir, Multisegmented wellbore, FutureGen2 aquifer, ',
                    'Workflow: AoR, forward']),
    '56g': ''.join(['Analytical reservoir, Cemented wellbore, FutureGen2 aquifer, ',
                    'Workflow: AoR, forward']),
    '57a': ''.join(['LUT reservoir, Multisegmented wellbore, FutureGen2 AZMI, ',
                    'Workflow: TTFD, LHS']),
    '57b': ''.join(['LUT reservoir, Multisegmented wellbore, FutureGen2 AZMI, ',
                    'Workflow: TTFD, forward']),
    '57c': ''.join(['Analytical reservoir, Open wellbore, Generic aquifer, ',
                    'Workflow: TTFD, forward']),
    '58a': 'LUT reservoir, Open wellbore, Workflow: LeakageAssessment, forward',
    '58b': 'Analytical reservoir, Multisegmented wellbore, Workflow: LeakageAssessment, LHS',
    '58c': 'Analytical reservoir, Open wellbore, Workflow: LeakageAssessment, LHS',
    }
